### ISSUE TITLE
Failure to build post upgrade to QT5

### ISSUE THREAD

**Issue by shairozan** [tpisto/pdf-fill-form#21]
Now since the upgrade to 5, the application won't build. I just get failure on NPM install:

make: Entering directory '/app/node_modules/pdf-fill-form/build'
  CXX(target) Release/obj.target/pdf_fill_form/src/pdf-fill-form.o
In file included from ../src/pdf-fill-form.cc:2:0:
../src/NodePoppler.h:5:26: fatal error: QtCore/QBuffer: No such file or directory
compilation terminated. The image I'm using already has updated to qt5, but attempting to do the install for pdf-fill-form dies per the above

**Comment by AckerApple** [comment]
Wild guess, try the following, which is in the README:
```
brew linkapps qt5
```

```
brew link --force qt5
```

**Comment by shairozan** [comment]
Ubuntu system not Mac

**Comment by MichaelBuen** [comment]
@shairozan you might need to ```apt-get install build-essential```

**Comment by KShewengerz** [comment]
Im using **Ubuntu 14.04** (on my computer), I have encountered this problem on my installation and spent a day configuring on what went wrong. I dont know why, but when I shift to **Ubuntu 16.04** (on my laptop) and try installing it, it works well. The error didn't appear.

**Comment by Sigura** [comment]
Sorry, I did not saw https://github.com/tpisto/pdf-fill-form/issues/23

**Comment by shairozan** [comment]
@MichaelBuen Build-Essential is part of the system as well. I need to test it again since it's been a while though.

**Comment by metasansana** [comment]
@shairozan  I'm on Ubuntu as well, just got it to install. Do as @MichaelBuen  says [here](https://github.com/tpisto/pdf-fill-form/issues/23#issuecomment-259382139) only use the paths for your system. Also I think you need to have `qtbase5-dev`.

I got the paths by doing :
```sh
  dpkg -L qt5base5-dev 

```

**Comment by henry-mueller** [comment]
@metasansana 
Thanks so much!  This would have taken me awhile to figure out myself.

There is a typo:  qt5base5-dev should be qtbase5-dev

In case it helps others, my export statements ended up like this (YMMV, use dpkg to confirm like metasansana suggests):

export CPPFLAGS=-I/usr/include/qt5
export LDFLAGS=-L/usr/lib/x86_64-linux-gnu/
export PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig

**Comment by metasansana** [comment]
Typo fixed, thanks @henry-mueller .
